all: 1 2_1 2_2 3

1: 1_monte_carlo.py
	python 1_monte_carlo.py

2_1: 2_1_guassian_distribution.py
	python 2_1_guassian_distribution.py

2_2: 2_2_tank_arriving.py
	python 2_2_tank_arriving.py

3: 3_em.py
	python 3_em.py